# Linear algebra in python

In [1]:
import numpy as np


In [2]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

In [8]:
print(v1*v2)

[ 4 10 18]


In [9]:
print(np.dot(v1,v2))

32


In [10]:
print(np.cross(v1,v2))

[-3  6 -3]


In [16]:
magnitude = np.linalg.norm(v2)

In [17]:
print(magnitude)

8.774964387392123


In [29]:
A = np.array([[1,2,3],[4,5,6]])
print(A)
print()
B = np.array([[7, 8, 9], [10, 11, 12]])
print(B)

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]


In [33]:
C = np.cross(A,B)
print(C)

[[-6 12 -6]
 [-6 12 -6]]


In [34]:
A = np.array([[2,3],[4,-1]])
B = np.array([5,3])
x = np.linalg.solve(A,B)

In [35]:
print(x)

[1. 1.]


In [36]:
A = np.array([[2,1],[1,2]])
e_value, e_vectors = np.linalg.eig(A)

In [37]:
print(e_value)
print(e_vectors)

[3. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
